# Generated by Django 3.1.3 on 2020-12-07 18:35

import decks.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_quote', models.CharField(max_length=240)),
                ('original_language', models.CharField(max_length=50)),
                ('translated_quote', models.TextField(max_length=300)),
                ('translated_language', models.CharField(max_length=50)),
                ('audio_file_path', models.TextField(default='', max_length=1000)),
                ('image_file_path', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CardModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('anki_model_code', models.TextField(default={'card_type': 'Basic (and reversed card)', 'code': 1041609445, 'css': '\n        .card {\n        font-family: arial;\n        font-size: 20px;\n        text-align: center;\n        color: black;\n        background-color: white;\n        }\n        .media {\n        margin: 2px;\n        }\n    ', 'fields': [{'name': 'Question'}, {'name': 'Answer'}, {'name': 'MyMedia'}, {'name': 'MyAudio'}], 'templates': [{'afmt': '{{FrontSide}}<hr id="answer">{{Answer}}<br>{{MyAudio}}', 'name': 'Card 1', 'qfmt': '{{Question}}<br>{{MyMedia}}'}, {'afmt': '{{FrontSide}}<hr id="answer">{{Answer}}<br>{{Question}}<br>{{MyMedia}}', 'name': 'Card 3', 'qfmt': '{{MyAudio}}'}]})),
            ],
        ),
        migrations.CreateModel(
            name='IncomingCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(default=5)),
                ('ready_for_archive', models.BooleanField(default=False)),
                ('submitted_to_archive', models.BooleanField(default=False)),
                ('incoming_quote', models.CharField(max_length=200)),
                ('quote_received_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deck_made', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserDecks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_id', models.PositiveBigIntegerField(blank=True, default=decks.models.UserDecks.make_random_number)),
                ('ankiforge_deck_name', models.CharField(max_length=50)),
                ('anki_deck_name', models.CharField(max_length=50)),
                ('native_lang', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=50)),
                ('learnt_lang', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='es', max_length=50)),
                ('images_enabled', models.BooleanField(default=True)),
                ('audio_enabled', models.BooleanField(default=True)),
                ('model_code', models.ForeignKey(default={'card_type': 'Basic (and reversed card)', 'code': 1041609445, 'css': '\n        .card {\n        font-family: arial;\n        font-size: 20px;\n        text-align: center;\n        color: black;\n        background-color: white;\n        }\n        .media {\n        margin: 2px;\n        }\n    ', 'fields': [{'name': 'Question'}, {'name': 'Answer'}, {'name': 'MyMedia'}, {'name': 'MyAudio'}], 'templates': [{'afmt': '{{FrontSide}}<hr id="answer">{{Answer}}<br>{{MyAudio}}', 'name': 'Card 1', 'qfmt': '{{Question}}<br>{{MyMedia}}'}, {'afmt': '{{FrontSide}}<hr id="answer">{{Answer}}<br>{{Question}}<br>{{MyMedia}}', 'name': 'Card 3', 'qfmt': '{{MyAudio}}'}]}, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='model_code', to='decks.cardmodels')),
            ],
        ),
    ]
