# Generated by Django 3.1.3 on 2020-12-07 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdecks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_decks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomingcards',
            name='archived_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archived_card', to='decks.archivedcards'),
        ),
        migrations.AddField(
            model_name='incomingcards',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_deck', to='decks.userdecks'),
        ),
        migrations.AddField(
            model_name='incomingcards',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
