# Generated by Django 3.1.3 on 2020-12-12 13:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_auto_20201209_1820'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='incomingcards',
            managers=[
                ('readyforprocessobject', django.db.models.manager.Manager()),
            ],
        ),
    ]
