# Generated by Django 3.1.3 on 2020-11-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_auto_20201116_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdecks',
            name='anki_deck_name',
            field=models.CharField(default='missingdeckname', max_length=50),
        ),
        migrations.AddField(
            model_name='userdecks',
            name='ankiforge_deck_name',
            field=models.CharField(default='missingdeckname', max_length=50),
        ),
    ]
