# Generated by Django 3.1.3 on 2020-12-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0004_auto_20201212_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdecks',
            name='learnt_lang',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('ja', 'Japanese'), ('zh-CN', 'Chinese (Simplified)'), ('zh-TW', 'Chinese (Traditional)'), ('de', 'German'), ('it', 'Italian'), ('fr', 'French')], default='es', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdecks',
            name='native_lang',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('ja', 'Japanese'), ('zh-CN', 'Chinese (Simplified)'), ('zh-TW', 'Chinese (Traditional)'), ('de', 'German'), ('it', 'Italian'), ('fr', 'French')], default='en', max_length=50),
        ),
    ]
