# Generated by Django 3.1.3 on 2020-12-16 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0005_auto_20201216_1753'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='incomingcards',
            managers=[
            ],
        ),
    ]
