# Generated by Django 3.1.3 on 2020-11-17 19:48

import decks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0005_auto_20201117_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdecks',
            name='deck_id',
            field=models.PositiveBigIntegerField(blank=True, default=decks.models.UserDecks.make_random_number),
        ),
    ]
