# Generated by Django 3.1.3 on 2020-11-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0006_auto_20201117_1948'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='incomingcards',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='incomingcards',
            name='cost',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
