# Generated by Django 3.1.3 on 2020-12-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0008_mediatransactions_charecters_sent_detect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediatransactions',
            name='charecters_sent_detect',
            field=models.IntegerField(default=27),
        ),
    ]
