# Generated by Django 3.1.3 on 2021-01-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0010_auto_20201219_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivedcards',
            old_name='audio_file_path',
            new_name='aws_audio_file_path',
        ),
        migrations.RenameField(
            model_name='archivedcards',
            old_name='image_file_path',
            new_name='aws_image_file_path',
        ),
        migrations.AddField(
            model_name='archivedcards',
            name='universal_filename',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='archivedcards',
            name='upload_audio_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archivedcards',
            name='upload_image_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archivedcards',
            name='voiced_quote',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='archivedcards',
            name='voiced_quote_lang',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='mediatransactions',
            name='characters_sent_azure_voice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediatransactions',
            name='found_in_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediatransactions',
            name='voiced_quote_lang',
            field=models.CharField(default='unknown', max_length=10),
            preserve_default=False,
        ),
    ]
