# Generated by Django 3.1.3 on 2021-01-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0011_auto_20210110_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedcards',
            name='universal_filename',
        ),
        migrations.AddField(
            model_name='archivedcards',
            name='image_search_phrase_string',
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='archivedcards',
            name='retrieved_image_url',
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='archivedcards',
            name='universal_audio_filename',
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='archivedcards',
            name='universal_image_filename',
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mediatransactions',
            name='audio_found_in_db',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediatransactions',
            name='image_found_in_db',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='archivedcards',
            name='aws_audio_file_path',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='archivedcards',
            name='aws_image_file_path',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='archivedcards',
            name='voiced_quote',
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='archivedcards',
            name='voiced_quote_lang',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
