# Generated by Django 3.1.3 on 2021-01-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0012_auto_20210118_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedcards',
            name='aws_audio_file_path',
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='archivedcards',
            name='aws_image_file_path',
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
    ]
