# Generated by Django 3.1.3 on 2021-01-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0013_auto_20210118_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediatransactions',
            name='found_in_archive',
        ),
    ]
