# Generated by Django 3.1.3 on 2021-01-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0014_remove_mediatransactions_found_in_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedcards',
            name='local_audio_file_path',
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='archivedcards',
            name='local_image_file_path',
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
    ]
