# Generated by Django 3.1.3 on 2021-02-01 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0016_forgeddecks'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingcards',
            name='forged_deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forged_deck', to='decks.forgeddecks'),
        ),
    ]
