# Generated by Django 3.1.3 on 2021-02-02 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0017_incomingcards_forged_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardmodels',
            name='anki_model_code',
        ),
        migrations.AlterField(
            model_name='userdecks',
            name='model_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_code', to='decks.cardmodels'),
        ),
    ]
