# Generated by Django 3.1.3 on 2021-02-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20210204_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='user_points',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
