# Generated by Django 3.1.3 on 2021-02-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20210204_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='stipe_customer_id',
            field=models.CharField(default='FAILED', max_length=255),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='stripe_subscription_id',
            field=models.CharField(default='FAILED', max_length=255),
        ),
    ]
