# Generated by Django 3.1.3 on 2021-03-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_auto_20210226_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripesubscription',
            old_name='stipe_customer_id',
            new_name='stripe_customer_id',
        ),
    ]
