# Generated by Django 3.1.3 on 2021-03-03 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_subscription_active_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='active_until',
        ),
    ]
